python launch.py --config configs/kiui/sd.yaml --train --gpu 1 system.prompt_processor.prompt="Iron man"
python launch.py --config configs/kiui/sd.yaml --train --gpu 1 system.prompt_processor.prompt="a DSLR photo of Joe Biden"
python launch.py --config configs/kiui/sd.yaml --train --gpu 1 system.prompt_processor.prompt="a DSLR photo of Marilyn Monroe"
python launch.py --config configs/kiui/sd.yaml --train --gpu 1 system.prompt_processor.prompt="a man wearing a striped shirt and grey linen pants"
python launch.py --config configs/kiui/sd.yaml --train --gpu 1 system.prompt_processor.prompt="a professional boxer"